modLoader="javafml"
loaderVersion="[35,)"
issueTrackerURL="https://github.com/TeamWizardry/WorldCrafter/issues"
logoFile="wizardry_logo.png"

[[mods]]
modId="worldcrafter"
displayName="World Crafter"
version="${version}"
authors="Team Wizardry"
credits="Escapee"
description='''
Create and customize your own in-world recipes
'''

[[dependencies.worldcrafter]]
    modId="forge"
    mandatory=true
    versionRange="[35.1.4,)"
    ordering="AFTER"
    side="BOTH"